name: Bug Report
labels: ["bug"]
description: 'Please use this template if you encountered rendering issues or glitches (not a crash or freeze)'
body:
  - type: input
    attributes:
      label: Citra Version
      description: 'The version of Citra you were using when the issue happened (can be found on the title bar)'
  - type: textarea
    attributes:
      label: Description
      description: 'Please describe what happened?'
      placeholder: |
        - Which game is this?
        - Does this issue also happen in the AppImage version?
        - What were you doing when the issue happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: System Information
      description: 'If possible, install `inxi`, run `inxi -v3` on your system and paste the output here'
      render: 'bash session'
    validations:
      required: false
  - type: textarea
    attributes:
      label: Logs
      description: |
        Please attach the Citra log file here (how to obtain it: https://community.citra-emu.org/t/how-to-upload-the-log-file/296)
        Please **avoid pasting the log** into this box. Instead, use the __file upload__ function to attach the file.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Remarks
      description: 'Do you have something notable to mention? Anything that will give us more context about this issue?'
    validations:
      required: false
